events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    server {
        listen       8080;
        server_name  localhost;
        
        # Ana sayfa
        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }
        
        # Sağlık durumu
        location /health/ {
            root   /usr/share/nginx/html;
            index  index.html;
        }
        
        # Statik dosyalar
        location /css/ {
            root   /usr/share/nginx/html;
            expires 1y;
        }
        
        location /js/ {
            root   /usr/share/nginx/html;
            expires 1y;
        }
        
        # Hata sayfaları
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}